name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual trigger
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: adithyasiva5
          outputs: |
            dist/snake.svg?color_snake=#00FF00&color_dots=#1A1A1A,#2B2B2B,#3C3C3C,#4D4D4D,#5E5E5E
      - uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
      - name: Commit and push the generated file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/snake.svg
          git commit -m "Update contribution snake animation"
          git push
